---
apiVersion: v1
kind: Service
metadata:
  namespace: federated-app
  name: k8s-demo-app
  labels:
    run: k8s-demo-app
spec:
  type: ClusterIP
  ports:
  - port: 8080
    targetPort: 80
    protocol: TCP
    name: http
  selector:
    run: k8s-demo-app
---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: federated-app
  name: k8s-demo-app
spec:
  selector:
    matchLabels:
      run: k8s-demo-app
  replicas: 1
  template:
    metadata:
      labels:
        run: k8s-demo-app
        datacenter: DC1
    spec:
      imagePullSecrets:
        - name: "{{pull_secret_name}}"
      containers:
      - name: nginxhttps
        image: docker-internal.app.yst.ntnx.local/nutanix-static-demo-app:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 443
          
---
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
    namespace: federated-app
    name: k8s-demo-app-ingress
spec:
    rules:
    - host: federated-app.karbon.yst.ntnx.local
      http:
        paths:
        - backend:
            serviceName: k8s-demo-app
            servicePort: 8080
          path: /